config/routes.rb
Rails.application.routes.draw do
  resources :set_lists
  resources :songs

end

app/models/set_list.rb
class SetList < ActiveRecord::Base
	has_and_belongs_to_many :songs
	validates :target_length_in_seconds, 
		numericality: { greater_than_or_equal_to: 0 } 
	validates :name, presence: true
end

app/models/song.rb
class Song < ActiveRecord::Base
	has_and_belongs_to_many :set_lists

	validates :length_in_seconds, numericality: { greater_than_or_equal_to: 0 }, presence: true
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end
end

app/controllers/set_lists_controller.rb
class SetListsController < ApplicationController
  before_action :set_set_list, only: [:show, :edit, :update, :destroy]

  # GET /set_lists
  # GET /set_lists.json
  def index
    # @set_lists = SetList.all
    render json: {:'set-lists' => SetList.all}
  end

  # GET /set_lists/1
  # GET /set_lists/1.json
  def show
  end

  # GET /set_lists/new
  def new
    @set_list = SetList.new
  end

  # GET /set_lists/1/edit
  def edit
  end

  # POST /set_lists
  # POST /set_lists.json
  def create
    @set_list = SetList.new(set_list_params)

    respond_to do |format|
      if @set_list.save
        format.html { redirect_to @set_list, notice: 'Set list was successfully created.' }
        format.json { render :show, status: :created, location: @set_list }
      else
        format.html { render :new }
        format.json { render json: @set_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /set_lists/1
  # PATCH/PUT /set_lists/1.json
  def update
    respond_to do |format|
      if @set_list.update(set_list_params)
        format.html { redirect_to @set_list, notice: 'Set list was successfully updated.' }
        format.json { render :show, status: :ok, location: @set_list }
      else
        format.html { render :edit }
        format.json { render json: @set_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /set_lists/1
  # DELETE /set_lists/1.json
  def destroy
    @set_list.destroy
    respond_to do |format|
      format.html { redirect_to set_lists_url, notice: 'Set list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_set_list
      @set_list = SetList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def set_list_params
      params.require(:set_list).permit(:name, :target_length_in_seconds)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    # respond_to do |format|
      # format.html { @songs = Song.all }
      # format.json { render json: {songs: Song.all} }
    # end
    render json: {songs: Song.all}
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :length_in_seconds)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/set_lists_helper.rb
module SetListsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LemieuxsicServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/set_lists/_form.html.erb
<%= form_for(@set_list) do |f| %>
  <% if @set_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@set_list.errors.count, "error") %> prohibited this set_list from being saved:</h2>

      <ul>
      <% @set_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :target_length_in_seconds %><br>
    <%= f.number_field :target_length_in_seconds %><br>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/set_lists/edit.html.erb
<h1>Editing Set List</h1>

<%= render 'form' %>

<%= link_to 'Show', @set_list %> |
<%= link_to 'Back', set_lists_path %>

app/views/set_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Set Lists</h1>

<table>
  <thead>
    <tr>
      <th>Target length in seconds</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @set_lists.each do |set_list| %>
      <tr>
        <td><%= set_list.target_length_in_seconds %></td>
        <td><%= link_to 'Show', set_list %></td>
        <td><%= link_to 'Edit', edit_set_list_path(set_list) %></td>
        <td><%= link_to 'Destroy', set_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Set list', new_set_list_path %>

app/views/set_lists/new.html.erb
<h1>New Set List</h1>

<%= render 'form' %>

<%= link_to 'Back', set_lists_path %>

app/views/set_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Target length in seconds:</strong>
  <%= @set_list.target_length_in_seconds %>
</p>

<%= link_to 'Edit', edit_set_list_path(@set_list) %> |
<%= link_to 'Back', set_lists_path %>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :length_in_seconds %><br>
    <%= f.number_field :length_in_seconds %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Length in seconds</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.length_in_seconds %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Length in seconds:</strong>
  <%= @song.length_in_seconds %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>